config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create] do
    resources :coinflips, only: [:create]
    resources :surveys, only: [:create, :new]
  end
  resources :data, only: [:index]
  resources :introduction, only: [:index]
  resources :thank_you, only: [:index]
  root 'introduction#index'
  
  get '/thanks', to: 'introduction#thanks'

end

app/models/coinflip.rb
class Coinflip < ActiveRecord::Base
  acts_as_xlsx
  belongs_to :user

  def convert(flip)
  	if flip then
  		return "Heads"
  	else
  		return "Tails"
  	end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  acts_as_xlsx
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_xlsx
  has_many :coinflips
  has_one  :survey

  def last_coin_flip_exists
    return self.coinflips.order(:created_at).last
  end

  def last_coin_flip_result
    last_coin_flip = last_coin_flip_exists
    return "Please flip" if !last_coin_flip
    return "Heads" if last_coin_flip.coin_result
    return "Tails"
  end

  def update_balance(bet_amount, did_win)
    begin
      delta = 1.0 * bet_amount
      delta = delta * -1.0 if did_win == false
      temp_balance = self.balance + delta
      self.balance = temp_balance.round(2)
    rescue
      self.balance = self.balance.round(2)
    end
  end

  def check_if_game_should_continue
    self.balance > 0
  end

  def balance_is_less_than_bet(bet)
    begin
      self.balance < bet
    rescue
      false
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coinflips_controller.rb
class CoinflipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    durationOfGame = Constants::GAME_MINUTE_DURATION.minutes + Constants::GAME_SECOND_DURATION.seconds
    timePassed = Time.now - durationOfGame
    if ((Time.now - durationOfGame) > @user.created_at) then
      redirect_to url_for(:controller => :surveys, :action => :new)
      return
    end

    @coinflip = @user.coinflips.new(user_params)
    if @user.balance_is_less_than_bet(@coinflip.bet) then
      flash[:error] = "Bet must be less than or equal to your balance"
      redirect_to user_path(@user) 
      return 
    end
    threshold_value=39
    @coinflip.coin_result = rand(100)>threshold_value
    @user.update_balance(@coinflip.bet, @coinflip.coin_result == @coinflip.winning_flip)
    @coinflip.balance = @user.balance
    @coinflip.save
    @user.save

    if @user.check_if_game_should_continue then
      redirect_to user_path(@user)
    else
      redirect_to url_for(:controller => :surveys, :action => :new)
    end
  end
 
  private
    def user_params
      params.require(:coinflip).permit(:bet, :winning_flip)
    end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @users = User.order(:id)
    respond_to do |format|
      format.html
      format.xlsx
    end
  end
end

app/controllers/introduction_controller.rb
class IntroductionController < ApplicationController
  def index
  end
  
  def thanks
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @survey = Survey.new(survey_params)
    @survey.user_id = params[:user_id]
    @survey.save
    @user.save
    if @user.save then
      redirect_to "/thank_you"
    end
  end
 
  private
    def survey_params
      params.require(:survey).permit(:test_for_response, :done_diff_response, :fam_with_response, :was_fair_response, :was_luck_response, :was_sensible_response, :own_money_response, :how_much_response, :exp_min_response, :thought_response, :stock_response, :stock_how_response, :general_comments)
    end
end

app/controllers/thank_you_controller.rb
class ThankYouController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.balance = Constants::STARTING_BALANCE
    @user.save
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name,:profession, :email, :age, :education)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coinflips_helper.rb
module CoinflipsHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/data/index.html.erb
<%= link_to "Download as Excel", data_path(format: "xlsx") %>
<table>  
  <% @users.each do |user| %>
    <tr>
      <th> "ID" </th>
      <th> "Name" </th>
      <th> "Email" </th>
      <th> "Age" </th>
      <th> "Profession" </th>
      <th> "Date"</th>
      <th> "Highest Level of Education" </th>
      <th> "What did you think we were testing for?" </th>
      <th> "Did you think the coin had 60% chance of coming up heads" </th>
      <th> "Do you think you were lucky?" </th>
      <th> "Did you think you bet sensibly" </th>
      <th> "What would you have done differently" </th>
      <th> "Would you have been willing to put money out of your own pocket to play and risk that money on flips" </th>
      <th> "If so, how much" </th>
      <th> "Did you give any thought to what the maximum would be?" </th>
      <th> "If yes, and assuming you just had one more session to play, how much money would you put into your balance to fund your playing session" </th>
      <th> "Do you think this game is similar to investing in the stock market?" </th>
      <th> "In what ways do you think it was dissimilar or similar?" </th>
      <th> "Have you heard of Kelly Criterion?" </th>
      <th> "General Comments" </th>
    </tr>
    <br>
    <tr>
      <td> <%= user.id %> </td>
      <td> <%= user.name %> </td>
      <td> <%= user.email %> </td>
      <td> <%= user.age %> </td>
      <td> <%= user.profession %> </td>
      <td> <%= user.created_at %> </td>
      <td> <%= user.education %> </td>
      <% if user.survey then%>
        <td> <%= user.survey.test_for_response %> </td>
        <td> <%= user.survey.was_fair_response %> </td>
        <td> <%= user.survey.was_luck_response %> </td>
        <td> <%= user.survey.was_sensible_response %> </td>
        <td> <%= user.survey.done_diff_response %> </td>
        <td> <%= user.survey.own_money_response %> </td>
        <td> <%= user.survey.how_much_response %> </td>
        <td> <%= user.survey.thought_response %> </td>
        <td> <%= user.survey.exp_min_response %> </td>
        <td> <%= user.survey.stock_response %> </td>
        <td> <%= user.survey.stock_how_response %> </td>
        <td> <%= user.survey.fam_with_response %> </td>
        <td> <%= user.survey.general_comments %> </td>
      <% end %>
    </tr>
    <th>Bets</th>
    <% user.coinflips.each do |coinflip| %>
      <tr>
        <% def heads_tails(flip)
          if flip then
            return "Heads"
          else
            return "Tails"
          end
        end %>

        <td>
          For User <%= coinflip.user_id %>
        </td>
        <td>
          <%= heads_tails(coinflip.coin_result) %>
        </td>
        <td>
          <%= coinflip.bet %>
        </td>
        <td>
          <%= heads_tails(coinflip.winning_flip) %> wins
        </td>
        <td>
          <%= coinflip.balance %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<style type="text/css">
  table, th, td {
    border: 1px solid black;
  }
</style>

app/views/introduction/index.html.erb
<div id="welcome-container">
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  <div id="welcome-text-container">
  <h1 id="title"> Welcome! </h1>
<br><p id="welcome-text">
Thank you for participating in this cognitive experiment we’re running, which will hopefully give us greater understanding of how people make decisions under uncertainty.  We will keep your personal details confidential.
<br><br>
You are being given $25 to give 30 minutes of your time to playing a coin flipping game. The $25 is real money and it will be put into your bank ‘balance’ in this game, and however much you have in the balance at the end of 30 minutes will be paid to you in cash or by check, up to a limit which we will tell you about if you get close to it. You can keep playing above that limit, but we will not pay you more than that limit, even if your balance is higher than that cap at the end.
<br><br>
<strong>The coin you can flip is programmed to have a 60% chance of coming up heads and a 40% chance of coming up tails. </strong>
<br><br>
You can bet any amount of money in your balance, but not more, on heads or tails on each flip.
<br><br>
If your balance goes to 0, you cannot play anymore, but we kindly request you stay in the room until the 30 minutes has elapsed.
<br><br> 
Please keep the details about this experiment confidential, so we don’t inadvertently have future subjects who know about the game in advance, as that will make our results less informative.
<br><br> 
If you have any questions, please ask one of us.
<br><br>
Thank you very much for your participation, and good luck!
</p>
	<br>
	<%= link_to "Accept", new_user_path %>
	</div>
</div>

app/views/introduction/thanks.html.erb
<div id="welcome-container">
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  <div id="welcome-text-container">
  <h1 id="title"> Thank you for participating! </h1>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoinFlip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="warning">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  	</div>

<%= yield %>

</body>
</html>

app/views/surveys/new.html.erb
<div id="welcome-container">
  
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  <div id="welcome-text-container">
  <% if @user.balance <= 0 then %>
    <h1 id="title"><span id="lost">Oops, you are bankrupt.</span> Thanks for playing!</h1><br>
  <% else %>
    <h1 id="title">You finished the game with <%= number_to_currency(@user.balance, :precision => 2) %>. Thanks for playing!</h1><br>
  <% end %> 
    
<%= form_for :survey, url: user_surveys_path do |f| %>

  <div>
    <%= f.label "What do you think we were testing for?", class:"q-labels",:autocomplete => :off, :required => true   %>
    <%= f.text_area(:test_for_response)%>
  </div>
  
  <p>
    <p class="q-labels">Do you think the coin did actually have a 60% chance of coming up heads?</p>
    <%= f.radio_button :was_fair_response, true, :class => "q-radio" %> 
    <%= label :was_fair_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :was_fair_response, false, :class => "q-radio"  %>
    <%= label :was_fair_response_false, 'No', :class => "q-radio" %>
  </p>
    
  <p>
    <p class="q-labels">Did you think you were lucky?</p>
    <%= f.radio_button :was_luck_response, true, :class => "q-radio"  %> 
    <%= label :was_luck_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :was_luck_response, false, :class => "q-radio"  %>
    <%= label :was_luck_response_false, 'No', :class => "q-radio"  %>
  </p>
    
  <p>
    <p class="q-labels">Did you think that you bet sensibly?</p>
    <%= f.radio_button :was_sensible_response, true, :class => "q-radio"  %> 
    <%= label :was_sensible_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :was_sensible_response, false, :class => "q-radio"  %>
    <%= label :was_sensible_response_false, 'No', :class => "q-radio"  %>
  </p>
  
  <div>
    <%= f.label "What would you have done differently?", class:"q-labels",:autocomplete => :off, :required => true   %>
    <%= f.text_area(:done_diff_response)%>
  </div>
      
  <p>
    <p class="q-labels">Would you have been willing to put up money out of your own pocket to play and risk that money on flips?</p>
    <%= f.radio_button :own_money_response, true, :class => "q-radio"  %> 
    <%= label :own_money_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :own_money_response, false, :class => "q-radio"  %>
    <%= label :own_money_response_false, 'No', :class => "q-radio"  %>
  </p>
  
  <div>
    <%= f.label "If yes, how much money would you have been willing to bet?", class:"q-labels",:autocomplete => :off %>
    <%= f.text_area(:how_much_response)%>
  </div>
      
  <p>
    <p class="q-labels">Did you give any thought to what the maximum we would pay you would be?</p>
    <%= f.radio_button :thought_response, true, :class => "q-radio"  %> 
    <%= label :thought_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :thought_response, false, :class => "q-radio"  %>
    <%= label :thought_response_false, 'No', :class => "q-radio"  %>
  </p>

  
  <div>
    <%= f.label "If yes, and assuming you just had one more session to play, how much money would you put into your balance to fund your playing session?", class:"q-labels",:autocomplete => :off %>
    <%= f.text_area(:exp_min_response)%>
  </div>
   
      
  <p>
    <p class="q-labels">Do you think this game is similar to investing in the stock market?</p>
    <%= f.radio_button :stock_response, 'yes', :class => "q-radio"  %> 
    <%= label :stock_response_yes, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :stock_response, 'little', :class => "q-radio"  %>
    <%= label :stock_response_little, 'A little bit', :class => "q-radio"  %>
    <%= f.radio_button :stock_response, 'no', :class => "q-radio"  %>
    <%= label :stock_response_no, 'No', :class => "q-radio"  %>
  </p>

  <div>
    <%= f.label "In what ways do you think it was similar / dissimilar", class:"q-labels",:autocomplete => :off %>
    <%= f.text_area(:stock_how_response)%>
  </div>
     
  <p>
    <p class="q-labels">Have you heard of Kelly Criterion?</p>
    <%= f.radio_button :fam_with_response, true, :class => "q-radio"  %> 
    <%= label :fam_with_response_true, 'Yes', :class => "q-radio"  %>
    <%= f.radio_button :fam_with_response, false, :class => "q-radio"  %>
    <%= label :fam_with_response_false, 'No', :class => "q-radio"  %>
  </p>

  <div>
    <%= f.label "Are there any other comments you would like to share with us?", class:"q-labels",:autocomplete => :off %>
    <%= f.text_area(:general_comments)%>
  </div>
    
   <p id="button">

        <%= f.submit "Submit", :id => "coinflip_submit" %>
  </p>
<% end %>
  </div>
</div>

app/views/thank_you/index.html.erb
<div id="welcome-container">
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  <div id="welcome-text-container">
  <h1 id="title"> Thank You! </h1>
<br><p id="welcome-text">
Thank you for participating in this cognitive experiment we’re running, which will hopefully give us greater understanding of how people make decisions under uncertainty.  We will keep your personal details confidential.
<br><br>

</div>

app/views/thank_you/new.html.erb
<div>
  <p>Thank you</p>
</div>

app/views/users/_coinflip.html.erb
<div id="welcome-container">
  
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  
    <p id="counter_css">Counter = <%= @user.coinflips.count %></p>
      
  
  <div id="coinflip-container">
    <h2 id="title">Place your bet and flip the coin</h2><br><br>
    <p id="hidden_maximum_winning_price" hidden> <%= Constants::MAXIMUM_WINNING_PRICE %> </p>
    <%= form_for([@user, @user.coinflips.build]) do |f| %>
        
        <p>
          <%= f.radio_button :winning_flip, true %> 
          <%= label :winning_flip_true, 'Heads', :id => "true_label" %>
          <%= f.radio_button :winning_flip, false %>
          <%= label :winning_flip_false, 'Tails' %>
        </p>
        
        <br>
        
        <p>
          <%= f.label :bet, :id => "bet_label" %>$<%= f.number_field :bet, :id => "bet_text_field",:autocomplete => :off, :value => "0", :min => "0.01", :max => @user.balance, :step => "0.01", :required => true %>
        </p>
        
        <br>   
        
        
        <p id="button">
      <% if @user.coinflips.count > 0 %>
        <%= f.submit "Flip", :id => "coinflip_submit_delay", :disabled => true %>
      <% else %>
        <%= f.submit "Flip", :id => "coinflip_submit" %>
      <% end %>
    </p>
        <% end %>
      
    <% if @user.coinflips.count > 0 %>
    <div id="right-container-load" hidden>  
    <% else %>
    <div id="right-container-load">  
    <% end %>
    <p id="balance">Balance : <br><span id="dollar">$</span><label id="total_balance"><%= @user.balance %> </label></p>          
  
  <% @user.coinflips.order("created_at desc").first(1).each do |coinflip| %>
    <% if coinflip.convert(coinflip.winning_flip) == coinflip.convert(coinflip.coin_result) %>
        <p id="coin-result">Well done, it's <span id="won"><%= @user.last_coin_flip_result %></span></p>
        <audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 4000)"><source src="http://elmfunds.com/upload/coinflip/cash.wav" ></audio>
      <% else %>
        <p id="coin-result">Sorry, it was <span id="lost"><%= @user.last_coin_flip_result %></span></p>
        <audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 4000)"><source src="http://elmfunds.com/upload/coinflip/boing.wav" ></audio>
        <% end %>
    <% end %>
    
    <br>
    
    </div>
    
    <div id="right-container-static">  
      
  <% if @user.coinflips.count > 0 %>
        <div id="animation"><img src="http://elmfunds.com/upload/coinflip/coin.gif" /></div> 
        <br><br>
        <% @user.coinflips.order("created_at desc").first(1).each do |coinflip| %>
        <p id="betting-on">You are betting <%= number_to_currency(coinflip.bet, :precision => 2) %> on <%= coinflip.convert(coinflip.winning_flip) %>...</p>
        <% end %>
        
  <% else %>
        <div id="animation"><img src="http://elmfunds.com/upload/coinflip/coin.gif" hidden/></div>
        
    <% end %>
    

    </div>
  
  <br><br><br>
  
  <% if @user.coinflips.count > 0 %>
  <table class="table table-hover" id="history-table" hidden>
  <% else %>
  <table class="table table-hover" id="history-table">
  <% end %>
  
  <tr>
    <th>Your Bet</th>
    <th>Bet Amount</th>
    <th>Result</th>
    <th>Won/Lost</th>
    <th>Ending Balance</th>
  </tr>
        
    <% @user.coinflips.order("created_at desc").each do |coinflip| %>
    <% if coinflip.persisted? then %>
  <tr>
           
            <td> <%= coinflip.convert(coinflip.winning_flip) %> </td>
            <td> <%= number_to_currency(coinflip.bet, :precision => 2) %> </td>
            <td> <%= coinflip.convert(coinflip.coin_result) %> </td>
      
      <% if coinflip.convert(coinflip.winning_flip) == coinflip.convert(coinflip.coin_result) %>
              <td id="won">Won</td>
            <% else %>
              <td id="lost">Lost</td>
            <% end %>
            
            <td> <%= number_to_currency(coinflip.balance, :precision => 2) %> </td>
            
          </tr>
    <% end %>
    <% end %>
    </table>

</div>

app/views/users/_timer.html.erb
<div id="timer"> 
  <p class="hidden-time" hidden><%= @user.created_at.to_f * 1000 %></p>
  <p class="hidden-minute-duration" hidden><%= Constants::GAME_MINUTE_DURATION %></p>
  <p class="hidden-second-duration" hidden><%= Constants::GAME_SECOND_DURATION %></p>
  <span>Time left = </span>
  <strong>
  <span id="minute"></span>
  <span>:</span>
  <span id="second"></span>
  </strong>
</div>

app/views/users/new.html.erb
<div id="welcome-container">
  <img id="mountains" src="http://www.elmfunds.com/img/bg4.jpg" />
  
  <div id="welcome-text-container">
  
  <h1 id="title"> Welcome! </h1>
  <%= form_for :user, url: users_path do |f| %>
  <br>
  <p>
    <%= f.label :name, class:"form-labels" %>
    <%= f.text_field :name, class:"form-fields",:autocomplete => :off, :required => true %>
  </p>
  <p>
    <%= f.label :email, class:"form-labels" %>
    <%= f.email_field :email, class:"form-fields",:autocomplete => :off, :required => true %>
  </p>
  <p>
    <%= f.label :age, class:"form-labels" %>
    <%= f.number_field :age, class:"form-fields",:autocomplete => :off, :required => true %>
  </p>
  <p>
    <%= f.label :education, class:"form-labels" %>
    <%= f.text_field :education, class:"form-fields",:autocomplete => :off, :required => true %>
  </p>
  <p>
    <%= f.label :profession, class:"form-labels" %>
    <%= f.text_field :profession, class:"form-fields",:autocomplete => :off, :required => true %>
  </p>
  <br>
   <p id="button">

        <%= f.submit "Continue", :id => "coinflip_submit" %>
  </p>
  <% end %>

</div>

app/views/users/show.html.erb
<%= render 'timer' %>

<%= render partial: 'coinflip' %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<%= form_for :user do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>